version: "3.7"
###   Find the docker-compose.yml for build in the root dir of this project.
services:
  web-app-test:
    container_name: web-app-test
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
    command: [ nginx-debug, '-g', 'daemon off;' ]
