version: "3.7"
###   Find the docker-compose.yml for build in the root dir of this project.
services:
  web-app-test:
    image: web-app-test:latest
    container_name: web-app-test
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-local
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./templates:/etc/nginx/templates
    command: [ nginx-debug, '-g', 'daemon off;' ]
